# Generated by Django 4.1.2 on 2022-10-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('image_link', models.CharField(max_length=500)),
                ('genres', models.CharField(max_length=120)),
                ('facebook_link', models.URLField(max_length=500)),
                ('website', models.URLField(max_length=120)),
                ('seeking_venue', models.BooleanField()),
                ('seeking_description', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('genres', models.CharField(max_length=120)),
                ('facebook_link', models.URLField(max_length=500)),
                ('image_link', models.CharField(max_length=500)),
                ('website', models.URLField(max_length=500)),
                ('seeking_description', models.CharField(max_length=500)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mzikiapp.artist')),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='mzikiapp.artist')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='mzikiapp.venue')),
            ],
            options={
                'db_table': 'show',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mzikiapp.venue'),
        ),
    ]
